apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aws-agent-config
spec:
  type: configuration.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: redisDB
    value: "3"
scopes:
- aws-agent
