services:
  resource-manager:
    image: resource-manager
    container_name: resource-manager
    build:
      context: .
      dockerfile: src/ResourceManager/Dockerfile
    ports:
      - 5000:5000 
  aws-agent:
    image: aws-agent
    container_name: aws-agent
    build:
      context: .
      dockerfile: src/AwsAgent/Dockerfile
    environment:
      - SERVICEOPTION__DBNAME=resource_topology
      - SERVICEOPTION__WORKERINTERVAL=1
      - SERVICEOPTION__RUNSINGLE=false
      - SERVICEOPTION__AWSCONFIGSUPPORTED=true
      - SERVICEOPTION__MAXCONCURRENTADAPTERS=5
      - SERVICEOPTION__REGION=cn-north-1
      - SERVICEOPTION__ACCESSKEYID=${ACCESS_KEY_ID}
      - SERVICEOPTION__SECRETACCESSKEY=${SECRET_ACCESS_KEY}
      - CONNECTIONSTRINGS__MONGODB=${AWSAGENT_MONGODB_URL}
