services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  resource-manager:
    image: resource-manager
    container_name: resource-manager
    build:
      context: .
      dockerfile: src/ResourceManager/Dockerfile
    ports:
      - "5000:5000"
      - "50002:50002"
    depends_on:
      - redis
      - placement

  resource-manager-dapr:
    image: "daprio/daprd"
    container_name: resource-manager-dapr
    network_mode: "service:resource-manager"
    depends_on:
      - resource-manager
    command: ["./daprd",
      "-app-id", "resource-manager",
      "-app-port", "5000",
      "-actors-service", "placement:50006",
      "-resources-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"

  aws-agent:
    image: aws-agent
    container_name: aws-agent
    build:
      context: .
      dockerfile: src/AwsAgent/Dockerfile
    depends_on:
      - redis
      - placement
    ports:
      - "50001:50001"
    environment:
      - SERVICEOPTION__WORKERINTERVAL=5

  aws-agent-dapr:
    image: "daprio/daprd"
    container_name: aws-agent-dapr
    network_mode: "service:aws-agent"
    depends_on:
      - aws-agent
    command: ["./daprd",
      "-app-id", "aws-agent",
      "-actors-service", "placement:50006",
      "-resources-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"

  placement:
    container_name: placement
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
      
networks:
  default:
    name: dapr-network