services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dapr/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmqdata:/var/lib/rabbitmq/
      - rabbitmqlog:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 10
      timeout: 30s
      start_period: 10s

  resource-manager:
    image: resource-manager
    container_name: resource-manager
    build:
      context: .
      dockerfile: src/ResourceManager/Dockerfile
    ports:
      - "5000:5000"
      - "50001:50001"
    depends_on:
      - placement

  resource-manager-dapr:
    image: "daprio/daprd"
    container_name: resource-manager-dapr
    network_mode: "service:resource-manager"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["./daprd",
      "-app-id", "resource-manager",
      "-app-port", "5000",
      "-log-level", "warn",
      "-actors-service", "placement:50006",
      "-resources-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/secrets/:/secrets"

  aws-agent:
    image: aws-agent
    container_name: aws-agent
    build:
      context: .
      dockerfile: src/AwsAgent/Dockerfile
    depends_on:
      - placement
    ports:
      - "5001:5000"
      - "50002:50001"
    environment:
      - SERVICEOPTION__WORKERINTERVAL=5
      - DAPR_GRPC_PORT=50001

  aws-agent-dapr:
    image: "daprio/daprd"
    container_name: aws-agent-dapr
    network_mode: "service:aws-agent"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["./daprd",
      "-app-id", "aws-agent",
      "-log-level", "warn",
      "-dapr-grpc-port", "50001",
      "-actors-service", "placement:50006",
      "-scheduler-host-address", "scheduler-0:50007",
      "-resources-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/secrets/:/secrets"

  scheduler-0:
    image: "daprio/dapr:1.14.4"
    container_name: ascheduler-0
    user: "1000:1000"
    command: ["./scheduler", 
      "--etcd-data-dir", "/tmp/dapr/scheduler",
      "--initial-cluster", "scheduler-0=http://scheduler-0:2380",
      "--replica-count", "1",
      "--id","scheduler-0",
      "--log-level", "warn",
      "--port", "50007"
    ]
    ports:
      - "50007:50007"
    volumes: 
      - ./dapr_scheduler/0:/tmp/dapr/scheduler

  placement:
    container_name: placement
    image: "daprio/dapr"
    command: ["./placement",
      "-log-level", "warn",
      "-port", "50006"
      ]
    ports:
      - "50006:50006"
      
networks:
  default:
    name: dapr-network

volumes:
  rabbitmqdata:
  rabbitmqlog: