services:
  resource-manager:
    image: resource-manager
    container_name: resource-manager
    build:
      context: .
      dockerfile: src/ResourceManager/Dockerfile
    ports:
      - 5000:5000 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  aws-agent:
    image: aws-agent
    container_name: aws-agent
    build:
      context: .
      dockerfile: src/AwsAgent/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
