apiVersion: v1
kind: Service
metadata:
  labels:
    service: aws-agent
  name: aws-agent
spec:
  selector:
    service: aws-agent
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: aws-agent
  name: aws-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      service: aws-agent
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "aws-agent" 
        dapr.io/grpc-port: "50001" # default
        dapr.io/log-level: "warn"
        dapr.io/enable-api-logging: "true"
      labels:
        service: aws-agent
    spec:
      containers:
      - name: aws-agent
        image: aws-agent
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
        env:
        - name: ConnectionStrings__Mongodb
          valueFrom:
            secretKeyRef:
              name: aws-agent-secret
              key: Mongodb
        - name: ServiceOption__AccessKeyId
          valueFrom:
            secretKeyRef:
              name: aws-agent-secret
              key: AccessKeyId
        - name: ServiceOption__SecretAccessKey
          valueFrom:
            secretKeyRef:
              name: aws-agent-secret
              key: SecretAccessKey
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: aws-agent-config
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  name: aws-agent-config
  labels:
    service: aws-agent
data:
  appsettings.json: |+
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "ServiceOption": {
        "DBName": "resource_topology",
        "Region": "cn-north-1",
        "WorkerInterval": 60,
        "RunSingle": false,
        "AwsconfigSupported": true,
        "MaxConcurrentAdapters": 5
      }
    }

---
