apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ include "resource-chart.fullname" . }}-secret
  labels:
  {{- include "resource-chart.labels" . | nindent 4 }}
scopes:
- aws-agent
spec:
  metadata: []
  type: secretstores.kubernetes
  version: v1