apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ include "resource-chart.fullname" . }}-state
  labels:
  {{- include "resource-chart.labels" . | nindent 4 }}
auth:
  secretStore: kubernetes
scopes:
- aws-agent
spec:
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: redisDB
    value: "0"
  - name: actorStateStore
    value: "true"
  - name: outboxPublishPubsub
    value: resource-agent
  - name: outboxPublishTopic
    value: resources
  type: state.redis
  version: v1