apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-chart.fullname" . }}-redis
  labels:
    app: redis
  {{- include "resource-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  selector:
    app: redis
    {{- include "resource-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.redis.ports | toYaml | nindent 2 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "resource-chart.fullname" . }}-redis
  labels:
  {{- include "resource-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  serviceName: {{ include "resource-chart.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.redis.redis.image.repository }}:{{ .Values.redis.redis.image.tag
          | default .Chart.AppVersion }}
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ include "resource-chart.fullname" . }}-redis-data
  updateStrategy: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "resource-chart.fullname" . }}-redis-data
  labels:
    service: redis-data
  {{- include "resource-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.redisData.storageRequest | quote }}