apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "resource-chart.fullname" . }}-secret-reader
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dapr
  {{- include "resource-chart.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list