apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aws-agent-secret
  namespace: default
spec:
  type: secretstores.local.env
  version: v1
  metadata:
    - name: prefix
      value: "AWS_AGENT_"