apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kube-agent-state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: redisDB
    value: "0"
  - name: actorStateStore
    value: "true"
  - name: outboxPublishPubsub
    value: resource-agent
  - name: outboxPublishTopic
    value: resources
auth:
  secretStore: kubernetes
scopes:
- kube-agent