apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aws-agent-state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    secretKeyRef:
      name: redis_password
  - name: redisDB
    value: "0"
  - name: actorStateStore
    value: "true"
  - name: outboxPublishPubsub
    value: resource-agent
  - name: outboxPublishTopic
    value: resources
auth:
  secretStore: aws-agent-secret
