apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
    secretKeyRef:
      name: redis_password
  - name: actorStateStore
    value: "true"
  - name: outboxPublishPubsub
    value: resource-agent
  - name: outboxPublishTopic
    value: resources
auth:
  secretStore: localsecretstore