apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: resource-agent
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: protocol
    value: amqp  
  - name: hostname
    value: rabbitmq 
  - name: username
    secretKeyRef:
      name: mq_user
  - name: password
    secretKeyRef:
      name: mq_password
  - name: durable
    value: true
  - name: deliveryMode
    value: 2
  - name: enableDeadLetter
    value: true
auth:
  secretStore: pubsub-secret
